eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  tomcat:
    max-threads: 500
    min-spare-threads: 50
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gszh?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true         
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    max-idle: 10
    min-idle: 5
    test-on-borrow: true
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  redis:
    host: 192.168.77.128
    port: 6379
    password: gszh8899

  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: admin
    password: admin
    
  zipkin: 
    base-url: http://127.0.0.1:5001
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: panda-auth,panda-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#关闭验证
management:
  metrics:
    web:
      server:
        auto-time-requests: false
